### ISSUE TITLE
As a non java programmer, can you tell me how to run this?

### ISSUE THREAD

**Issue by kmace** [sixhat/ChessInfluenceViewer#1]

**Comment by sixhat** [comment]
@kmace the best way to run this is to use eclipse https://www.eclipse.org/ , create a new project, import this source code into it and run it from there. Otherwise you'll need to compile it and run it from the command line.

**Comment by deeredman1991** [comment]
@sixhat You wouldn't happen to have a link to a tutorial on how to import it would you? I'm trying to import the files into eclipse and it's saying "The selection cannot be launched, and there are no recent launches." when trying to run.

**Comment by sixhat** [comment]
Hi, there is a tutorial on how to run programs in eclipse here https://www.tutorialspoint.com/eclipse/eclipse_running_program.htm In this case you have to run Civ.java as it is the entry point (main method)

**Comment by sixhat** [comment]
You can also try to import the project into eclipse as "General / Projects from Folder or Archive", then right clicking on Civ.java will let you run it as a Java Application.
